services:
  - type: web
    name: ai-prompt-backend
    env: java
    plan: free
    rootDirectory: backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar --spring.profiles.active=prod
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 10000
    healthCheckPath: /api/prompts/health